---
title: "Day 2 Computational Session - Making and Indexing in R"
author: "Desik Somasundaram"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## Make some vectors & cheack them out

```{r}

sixers <- c("Embiid", "Harris", "Simmons", "Maxey")

ppg <- c(29.5, 21.2, 13.6, 10.0)

# Check the class:
class(sixers)
class(ppg)
typeof(ppg)

is.character(sixers)

```
```{r}
positions <- c(Embiid = "center",
               Harris = "small forward",
               Simmons = "power forward",
               Maxey = "point guard"
               )

positions

positions[2]

positions["Embiid"]
```
```{r}

cars <- c("red", "green", "blue", "silver", "white", "black")

cars[2:5]

i <- 3
cars[i]

i <- c(1,5,6)
cars[i]

cars[3] <- "galactica"

cars


```
## Lists in R

```{r}

urchins <- list("blue", 
                c(1,2,3) ,
                seq(from = 0, to = 50, by = 0.5), 
                TRUE, 1200L)

urchins

#list item
urchins[[3]]

# one element list
urchins[3]

```

```{r}
tacos <- list(topping = c("onion", "cilantro", "guacamole"),
              filling = c("beans", "meat", "veggies"),
              price = c(6.75, 8.25, 9.50))

tacos

taco_price <- tacos[[3]]

tacos$price


```
## Data frames

```{r}
fruit <- data.frame(type = c("guava", "strawberry", "mango"),
                    mass = c(100, 30, 200))

fruit

class(fruit)

class(fruit$mass)

fruit$type
fruit[,1]
fruit[1,]

```

